image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - front-end/node_modules/

build_front_end:
  stage: build
  script:
    - cd front-end
    - npm install
    - npm run-script build

backend_unit_tests:
  stage: test
  image: python:3.6-stretch
  before_script:
    - pip install -r back-end/requirements.txt
  script:
    - make python-tests