image: node:latest

stages:
  - build
  - test

cache:
  paths:
    - front-end/node_modules/

build_front_end:
  stage: build
  script:
    - cd front-end
    - npm install
    - npm run-script build

frontend_gui_test:
  stage: test
  image: python:3.6-stretch
  script:
  - cd frontend
  - pip3 install selenium
  # ripped straight from https://gitlab.com/10AMGroup11/bookrus/-/blob/main/.gitlab-ci.yml
  # Add chrome to container
  - wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | apt-key add -
  - sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
  - apt-get -y update
  - apt-get install -y google-chrome-stable

  # Download and unzip the chromedriver
  - apt-get install -yqq unzip
  - wget -O /tmp/chromedriver.zip http://chromedriver.storage.googleapis.com/`curl -sS chromedriver.storage.googleapis.com/LATEST_RELEASE`/chromedriver_linux64.zip
  - unzip /tmp/chromedriver.zip chromedriver -d /usr/local/bin/

  # Run selenium tests
  - python3 guitests.py


backend_unit_tests:
  stage: test
  image: python:3.6-stretch
  before_script:
    - pip install -r back-end/requirements.txt
  script:
    - make python-tests