import Avatar from "../assets/placeholder/avatar.png"

// inspired by TexasVotes project. https://gitlab.com/forbesye/fitsbits/-/blob/master/front-end/src/views/About/AboutInfo.js

const teamInfo = [
  {
    name: "Cole Amlong",
    gitlab_username: "coleamlong",
    email: "coleamlong@gmail.com",
    image: Avatar,
    role: "Front-end",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ullamcorper purus interdum orci auctor, id venenatis sem congue. Morbi condimentum mi non risus bibendum, accumsan tincidunt lacus suscipit.",
    commits: 0,
    issues: 0,
    unit_tests: 0,
  },
  {
    name: "Faiza Rahman",
    gitlab_username: "faiza2002",
    email: "---",
    image: Avatar,
    role: "---",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ullamcorper purus interdum orci auctor, id venenatis sem congue. Morbi condimentum mi non risus bibendum, accumsan tincidunt lacus suscipit.",
    commits: 0,
    issues: 0,
    unit_tests: 0,
  },
  {
    name: "Mikala Jaramillo",
    gitlab_username: "Mikalajj",
    email: "---",
    image: Avatar,
    role: "---",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ullamcorper purus interdum orci auctor, id venenatis sem congue. Morbi condimentum mi non risus bibendum, accumsan tincidunt lacus suscipit.",
    commits: 0,
    issues: 0,
    unit_tests: 0,
  },
  {
    name: "Sarthak Sirotiya",
    gitlab_username: "sarthaksirotiya",
    email: "---",
    image: Avatar,
    role: "---",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ullamcorper purus interdum orci auctor, id venenatis sem congue. Morbi condimentum mi non risus bibendum, accumsan tincidunt lacus suscipit.",
    commits: 0,
    issues: 0,
    unit_tests: 0,
  },
  {
    name: "Thomas Langford",
    gitlab_username: "thomas_langford",
    email: "---",
    image: Avatar,
    role: "---",
    bio: "Lorem ipsum dolor sit amet, consectetur adipiscing elit. Etiam ullamcorper purus interdum orci auctor, id venenatis sem congue. Morbi condimentum mi non risus bibendum, accumsan tincidunt lacus suscipit.",
    commits: 0,
    issues: 0,
    unit_tests: 0,
  },
]